import type { Hostel } from './types';

export const hostels: Hostel[] = [
  {
    id: '1',
    name: 'Apna Ghar Hostel',
    address: '123, Rajiv Gandhi Nagar',
    distance: 1.2,
    rating: 4.5,
    price: 8000,
    facilities: { ac: true, wifi: true, food: true },
    imageUrl: 'https://placehold.co/600x400.png',
    ownerId: 'owner1',
  },
  {
    id: '2',
    name: 'Students Paradise',
    address: '45, Dadabari Main Rd',
    distance: 0.8,
    rating: 4.8,
    price: 9500,
    facilities: { ac: true, wifi: true, food: true },
    imageUrl: 'https://placehold.co/600x400.png',
    ownerId: 'owner1',
  },
  {
    id: '3',
    name: 'Shanti Niwas',
    address: '78, Jawahar Nagar',
    distance: 2.5,
    rating: 4.2,
    price: 7000,
    facilities: { ac: false, wifi: true, food: true },
    imageUrl: 'https://placehold.co/600x400.png',
    ownerId: 'owner2',
  },
  {
    id: '4',
    name: 'Kota Comforts',
    address: '91, Indra Vihar',
    distance: 0.5,
    rating: 4.9,
    price: 12000,
    facilities: { ac: true, wifi: true, food: true },
    imageUrl: 'https://placehold.co/600x400.png',
    ownerId: 'owner2',
  },
  {
    id: '5',
    name: 'The Nest',
    address: '23, Talwandi Circle',
    distance: 1.8,
    rating: 4.0,
    price: 7500,
    facilities: { ac: true, wifi: false, food: true },
    imageUrl: 'https://placehold.co/600x400.png',
    ownerId: 'owner1',
  },
  {
    id: '6',
    name: 'Scholar\'s Den',
    address: '56, Vigyan Nagar',
    distance: 3.0,
    rating: 4.3,
    price: 6500,
    facilities: { ac: false, wifi: true, food: false },
    imageUrl: 'https://placehold.co/600x400.png',
    ownerId: 'owner2',
  },
];

export const coachingCenters = [
    { name: 'Allen Career Institute', location: 'Rajiv Gandhi Nagar' },
    { name: 'Resonance', location: 'Indra Vihar' },
    { name: 'Bansal Classes', location: 'Dadabari' },
    { name: 'FIITJEE', location: 'Talwandi' },
];
